[build]
target-dir = "target"
rustflags = ["-C", "link-arg=-Wl,-rpath,/home/rust/libtorch/lib"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-Wl,-rpath,/home/rust/libtorch/lib"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
 
[env]
CXXFLAGS = "-std=c++17"
LIBTORCH = "/home/rust/libtorch"
LD_LIBRARY_PATH = "/home/rust/libtorch/lib" 